const API = 'http://localhost:8000';
let token = localStorage.getItem('applyai_token') || '';
const labels = {dashboard:'Dashboard',auth:'Authentication',jobs:'Job analyzer',resumes:'Resumes',applications:'Applications',profile:'Profile'};
const $ = id => document.getElementById(id);
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active')); $(id).classList.add('active'); document.querySelectorAll('aside button').forEach(b=>b.classList.toggle('active',b.dataset.page===id)); $('crumb').textContent=labels[id]; if(id==='resumes') loadResumes(); if(id==='applications') loadApplications(); if(id==='dashboard') loadSummary();}
async function api(path, options={}){const headers={...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{})}; const response=await fetch(API+path,{...options,headers}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.detail||data.message||'Request failed'); return data;}
function message(id,text,error=false){$(id).textContent=text; $(id).className=error?'error':'success';}
async function register(){try{const d=await api('/api/auth/register',{method:'POST',body:JSON.stringify({full_name:$('authName').value,email:$('authEmail').value,password:$('authPassword').value})}); token=d.token; localStorage.setItem('applyai_token',token); $('userLabel').textContent=d.user.full_name; message('authMessage','Registered successfully'); showPage('dashboard');}catch(e){message('authMessage',e.message,true)}}
async function login(){try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('authEmail').value,password:$('authPassword').value})}); token=d.token; localStorage.setItem('applyai_token',token); $('userLabel').textContent=d.user.full_name; message('authMessage','Logged in successfully'); showPage('dashboard');}catch(e){message('authMessage',e.message,true)}}
async function saveProfile(){try{await api('/api/profile',{method:'POST',body:JSON.stringify({first_name:$('firstName').value,last_name:$('lastName').value,phone:$('phone').value,location:$('location').value,education:$('education').value,experience:$('experience').value,linkedin:$('linkedin').value,github:$('github').value,work_authorization:$('workAuth').value})}); message('profileMessage','Profile saved');}catch(e){showPage('auth');message('authMessage','Please sign in first',true)}}
async function uploadResume(){try{const file=$('resumeFile').files[0];if(!file) throw Error('Choose a file');const form=new FormData();form.append('file',file);await api('/api/resumes',{method:'POST',body:form}); loadResumes();}catch(e){alert(e.message)}}
async function loadResumes(){try{const d=await api('/api/resumes');$('statResumes').textContent=d.data.length;$('resumeList').innerHTML=d.data.map(r=>`<div class="row"><b>${escapeHtml(r.name)}</b><span>${r.skills.join(', ')||'No skills detected'}</span></div>`).join('')||'<p>No resumes uploaded.</p>'}catch(e){$('resumeList').textContent='Sign in to load resumes.'}}
async function createJob(){try{const d=await api('/api/jobs',{method:'POST',body:JSON.stringify({url:$('jobUrl').value,title:$('jobTitle').value||'Unknown role',company:$('jobCompany').value||'Unknown company',location:$('jobLocation').value,description:$('jobDescription').value})}); const job=d.data; const matches=await api(`/api/jobs/${job.id}/matches`,{method:'POST'});$('jobResult').innerHTML=`<div class="result"><h3>${escapeHtml(job.title)} at ${escapeHtml(job.company)}</h3><p>${job.blocker?`Blocked: ${job.blocker}`:'No blocker detected'}</p>${matches.data.map(m=>`<div class="row"><span>${escapeHtml(m.resume_name)}<br><small>${m.matched.join(', ')}</small></span><b class="green">${m.score}%</b><button class="secondary" onclick="createApplication(${job.id},${m.resume_id})">Review</button></div>`).join('')}</div>`}catch(e){alert(e.message)}}
async function createApplication(jobId,resumeId){try{const d=await api('/api/applications',{method:'POST',body:JSON.stringify({job_id:jobId,resume_id:resumeId,approved:false})});alert(`Application ${d.data.status}. Review the fields, then approve through the API or your future review screen.`);showPage('applications');loadApplications()}catch(e){alert(e.message)}}
async function loadApplications(){try{const d=await api('/api/applications');$('statApps').textContent=d.data.length;$('statReview').textContent=d.data.filter(a=>a.status==='awaiting_review').length;$('applicationList').innerHTML=d.data.map(a=>`<div class="row"><span>Job #${a.job_id} · Resume #${a.resume_id}<br><small>${a.notes||''}</small></span><span class="badge">${a.status}</span></div>`).join('')||'<p>No applications.</p>'}catch(e){$('applicationList').textContent='Sign in to load applications.'}}
async function loadSummary(){if(token){loadResumes();loadApplications()}}
function downloadExport(){if(!token)return showPage('auth');window.open(`${API}/api/export/applications.csv?token=${encodeURIComponent(token)}`,'_blank')}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
document.querySelectorAll('aside button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));if(!token)showPage('auth');else showPage('dashboard');
